ALTER TABLE brand_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE question_answers DISABLE ROW LEVEL SECURITY;
ALTER TABLE documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE reports DISABLE ROW LEVEL SECURITY;
